try {
  hello();
} catch(error) {
  console.log(error);
}

try {
  anotherFun();
} catch {
  console.log('esto es un error');
}

